import { FormEvent, useEffect, useReducer, useState } from 'react'
import Head from "next/head";
import AdminLayout from "@/layouts/AdminLayout"
import AuthHOC from '@/components/AuthHOC'
import Button from '@/components/Button';
import { useRouter } from 'next/router';
import { IWinner, IReducerAction } from '@/interfaces'
import usePost from '@/hooks/usePost';
import { toast } from 'react-toastify';
import Loader from '@/components/Loader';



const initialState: IWinner = {
    email: '',
    name: '',
    position: '',
    category: '',
    image: '',
}

type IAction = 'email' | 'name' | 'position' | 'category' | 'image' | 'reset'

const AddWinner = () => {
    const [winner, dispatch] = useReducer((state: IWinner, action: IReducerAction<IAction>) => {
        if (action.type === 'reset') return initialState
        return { ...state, [action.type]: action.payload }
    }, initialState)

    const router = useRouter()
    const { loading, error, data, post } = usePost({ 
        api: "/winners",
        onSuccess: () => {
            toast('Winner Added')
            dispatch({ type: 'reset'})
        } 
    })

    const addWinner = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        post(winner)
    }

    

    return (
        <AdminLayout>
        <Head>
            <title>Brilliant Brains</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/faviconimg.png" />
        </Head>
        {loading && <Loader modalOpen={true} />}
        <div className='p-4 py-12 sm:px-12'>
            <div className="flex items-center gap-4 justify-between mb-16">
                <h1 className='text-3xl text-black/70 font-argentinum'>Add Winners</h1>
                <Button onClick={() => router.push("/admin/winners")} className="text-white px-4 sm:px-6 py-2 rounded-md text-sm">View Winners</Button>
            </div>
            <form className="flex flex-col gap-4" onSubmit={addWinner}>
                <div className="flex flex-col gap-1">
                    <label htmlFor="name" className="text-black/70">Name</label>
                    <input required onChange={(e) => dispatch({ type: 'name', payload: e.target.value })} value={winner?.name} type="text" name="name" id="name" className="border border-black/20 rounded-md p-2" />
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor="email" className="text-black/70">Email</label>
                    <input required onChange={(e) => dispatch({ type: 'email', payload: e.target.value })} value={winner?.email} type="email" name="email" id="email" className="border border-black/20 rounded-md p-2" />
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor="image" className="text-black/70">Image</label>
                    <input required onChange={(e) => dispatch({ type: 'image', payload: e.target.value })} value={winner?.image} type="text" name="image" id="image" className="border border-black/20 rounded-md p-2" />
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor="category" className="text-black/70">Category</label>
                    <select required onChange={(e) => dispatch({ type: 'category', payload: e.target.value })} value={winner?.category} name="category" id="category" className="border border-black/20 rounded-md p-2">
                        <option value="">--</option>
                        <option value="primary">Primary</option>
                        <option value="secondary">Secondary</option>
                        <option value="Undergraduate">Undergraduate</option>
                        <option value="Postgraduate">Postgraduate</option>
                    </select>
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor="position" className="text-black/70">Position</label>
                    <select required onChange={(e) => dispatch({ type: 'position', payload: e.target.value })} value={winner?.position} name="position" id="position" className="border border-black/20 rounded-md p-2">
                        <option value="">--</option>
                        <option value="1">1st Position</option>
                        <option value="2">2nd Position</option>
                        <option value="3">3rd Position</option>
                    </select>
                </div>
                {/* <div className="flex flex-col gap-1">
                    <label htmlFor="level" className="text-black/70">Level</label>
                    <select required onChange={(e) => dispatch({ type: 'email', payload: e.target.value })} value={winner?.name} name="level" id="level" className="border border-black/20 rounded-md p-2">
                        <option value="">--</option>
                        <option value="1">Level 1</option>
                        <option value="2">Level 2</option>
                        <option value="3">Level 3</option>
                    </select>
                </div> */}
                <div className="flex items-center gap-4 mt-8">
                    <Button type='submit' className="text-white px-4 sm:px-6 py-2 rounded-md text-sm">Add Winner</Button>
                    <button onClick={() => dispatch({ type: 'reset' })} className="text-black/60 px-4 sm:px-6 py-2 rounded-md text-sm">Clear</button>
                </div>
            </form>
        </div>
        </AdminLayout>
    );
}


export default AuthHOC(AddWinner)
