import Head from "next/head";
import AdminLayout from "@/layouts/AdminLayout"

export default function Home() {
  return (
    <AdminLayout>
      <Head>
        <title>Brilliant Brains</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconimg.png" />
      </Head>
      <div>
        <h1>Admin Page</h1>
      </div>
    </AdminLayout>
  );
}
