import { FormEvent, useEffect, useReducer, useState } from 'react'
import Head from "next/head";
import AdminLayout from "@/layouts/AdminLayout"
import AuthHOC from '@/components/AuthHOC'
import Button from '@/components/Button';
import { useRouter } from 'next/router';
import { ICms, IReducerAction } from '@/interfaces'
import usePost from '@/hooks/usePost';
import { toast } from 'react-toastify';
import Loader from '@/components/Loader';
import useImage from '@/hooks/useImage';
import Image from 'next/image';


const initialState: ICms = {
    _id: null,
    hero: {
        header: '',
        text: '',
        image: '',
    },
    about: {
        header: '',
        text: '',
        image: '',
    },
}

type IAction = 'hero' | 'about' | 'update'

const EditCms = () => {
    const [loading, setLoading] = useState(false)
    const [cms, dispatch] = useReducer((state: ICms, action: IReducerAction<IAction>) => {
        if (action.type === 'update' && typeof action.payload !== 'string') {
            return { ...state, ...action.payload }
        }
        return { ...state, [action.type]: action.payload }
    }, initialState)
    const { url: heroImage, uploadImage, error: errorImage, progress, setError, loading: uploadingImage } = useImage()
    const { url: aboutImage, uploadImage: uploadAboutImage, error: errorAboutImage, loading: uploadingAboutImage } = useImage()

    console.log({cms})

    const router = useRouter()
    const { loading: posting, error, data, post } = usePost({ 
        api: `/cms/${cms?._id || ''}`,
        method: 'PATCH',
        onSuccess: () => {
            toast('Updated successfully')
        }
    })

    const updateAbout = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        post({
            about: cms.about
        })
    }

    const updateHero = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        post({
            hero: cms.hero
        })
    }

    
    useEffect(() => {
        if (heroImage) {
            dispatch({ type: 'hero', payload: { ...cms.hero, image: heroImage } })
        }
    }, [heroImage])

    useEffect(() => {
        if (aboutImage) {
            dispatch({ type: 'about', payload: { ...cms.about, image: aboutImage } })
        }
    }, [aboutImage])

    useEffect(() => {
        const fetchData = async () => {
          try {
            setLoading(true)
            const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/cms`)
            const data = await res.json()
            
            if (!res.ok) throw new Error(data.message)
    
            console.log({data})
            dispatch({ type: 'update', payload: data[0] })
          } catch (error) {
            console.log({error})
          }
            setLoading(false)  
        }

    
        fetchData()
      }, [])



    return (
        <AdminLayout>
        <Head>
            <title>Brilliant Brains</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/faviconimg.png" />
        </Head>
        {(loading || posting || uploadingImage) && <Loader modalOpen={true} />}
        <div className='p-4 py-12 sm:px-12 h-full overflow-y-auto'>
            {/* <div className="flex items-center gap-4 justify-between mb-16">
                <h1 className='text-3xl text-black/70 font-argentinum'>Content Management System</h1>
            </div> */}
            <section className="pb-10 border-b">
                <h1 className='text-2xl text-black/70 font-argentinum mb-6'>Hero Section</h1>
                <form className="flex flex-col gap-4" onSubmit={updateHero}>
                    <div className="flex flex-col gap-1">
                        <label htmlFor="header" className="text-black/70">Header</label>
                        <input minLength={35} maxLength={45} required onChange={(e) => dispatch({ type: 'hero', payload: { ...cms.hero, header: e.target.value } })} value={cms?.hero?.header} type="text" name="header" id="header" className="border border-black/20 rounded-md p-2" />
                    </div>
                    <div className="flex flex-col gap-1">
                        <label htmlFor="text" className="text-black/70">Text</label>
                        <textarea minLength={200} maxLength={450} rows={3} required onChange={(e) => dispatch({ type: 'hero', payload: {...cms.hero, text: e.target.value } })} value={cms?.hero?.text} name="text" id="text" className="border border-black/20 rounded-md p-2" />
                        {/* <input minLength={200} maxLength={300} required onChange={(e) => dispatch({ type: 'hero', payload: {...cms.hero, text: e.target.value } })} value={cms?.hero?.text} type="text" name="text" id="text" className="border border-black/20 rounded-md p-2" /> */}
                    </div>
                    <div className="flex flex-col gap-1">
                        <span className="text-black/70">Image</span>
                        {/* <label className="border border-black/20 rounded-md p-2 min-h-[42px] max-h-12 whitespace-nowrap overflow-hidden bg-white" htmlFor="image">
                            click to change Image
                        </label> */}
                         {cms?.hero?.image &&
                            <Image width={100} height={100} src={cms?.hero?.image} alt="" className="h-24 w-24 bg-gray-100 object-cover z-10 relative" />
                         }
                        <input type='file' name='image' id='image' className='' onChange={(e) => uploadImage(e.target.files![0])} />
                        {/* {uploadingImage && <p>Uploading Image {progress}%</p>} */}
                    </div>
                    <div className="flex items-center gap-4">
                        <Button type='submit' className="text-white px-4 sm:px-6 py-2 rounded-xl text-sm">Update</Button>
                    </div>
                </form>
            </section>
            <section className="py-10 border-b">
                <h1 className='text-2xl text-black/70 font-argentinum mb-6'>About Section</h1>
                <form className="flex flex-col gap-4" onSubmit={updateAbout}>
                    <div className="flex flex-col gap-1">
                        <label htmlFor="header" className="text-black/70">Header</label>
                        <input minLength={35} maxLength={45} required onChange={(e) => dispatch({ type: 'about', payload: { ...cms.about, header: e.target.value } })} value={cms?.about?.header} type="text" name="header" id="header" className="border border-black/20 rounded-md p-2" />
                    </div>
                    <div className="flex flex-col gap-1">
                        <label htmlFor="text" className="text-black/70">Text</label>
                        <textarea minLength={200} maxLength={450} rows={3} required onChange={(e) => dispatch({ type: 'about', payload: { ...cms.about, text: e.target.value } })} value={cms?.about?.text} name="text" id="text" className="border border-black/20 rounded-md p-2" />
                        {/* <input minLength={200} maxLength={300} required onChange={(e) => dispatch({ type: 'about', payload: { ...cms.about, text: e.target.value } })} value={cms?.about?.text} type="text" name="text" id="text" className="border border-black/20 rounded-md p-2" /> */}
                    </div>
                    <div className="flex flex-col gap-1">
                        <span className="text-black/70">Image</span>
                        {/* <label className="border border-black/20 rounded-md p-2 min-h-[42px] max-h-12 whitespace-nowrap overflow-hidden bg-white" htmlFor="image">
                            {cms?.about?.image ? cms?.about?.image : ''}
                        </label> */}
                         {cms?.about?.image &&
                            <Image width={100} height={100} src={cms?.about?.image} alt="" className="h-24 w-24 bg-gray-100 object-cover z-10 relative" />
                         }
                        <input type='file' name='image' id='image' className='' onChange={(e) => uploadAboutImage(e.target.files![0])} />
                        {/* {uploadingImage && <p>Uploading Image {progress}%</p>} */}
                    </div>
                    <div className="flex items-center gap-4">
                        <Button type='submit' className="text-white px-4 sm:px-6 py-2 rounded-xl text-sm">Update</Button>
                    </div>
                </form>
            </section>
        </div>
        </AdminLayout>
    );
}


export default AuthHOC(EditCms)

// export async function getServerSideProps() {
//     let data
//     try {
//         const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/cms`)
//         data = await res.json()
        
//         if (!res.ok) throw new Error(data.message)

//         console.log({data})
    
//       } catch (error) {
//         console.log({error})
//         return {
//             props: {
//                 status: 'error',
//                 cms: data[0] || {}
//             }
//         }
//       }

//     return {
//         props: {
//             status: 'success',
//             cms: data[0] || {}
//         }
//     }

// }
