import { FormEvent, useEffect, useReducer, useRef, useState, useCallback } from 'react'
import Head from "next/head";
import AdminLayout from "@/layouts/AdminLayout"
import AuthHOC from '@/components/AuthHOC'
import Button from '@/components/Button';
import { useRouter } from 'next/router';
import { IAdvisory, IReducerAction } from '@/interfaces'
import usePost from '@/hooks/usePost';
import { toast } from 'react-toastify';
import Loader from '@/components/Loader';
import useImage from '@/hooks/useImage';
import { Editor as TinyMCEEditor } from 'tinymce';
import TinyEditor from '@/components/Editor';
import Image from 'next/image';


const initialState: IAdvisory = {
    email: '',
    name: '',
    image: '',
    number: '',
    title: '',
    description: '',
}

type IAction = 'email' | 'name' | 'image' | 'number' | 'title' | 'description' | 'reset' | 'update'

const EditBoardMember = () => {
    const [loading, setLoading] = useState(false)
    const [advisory, dispatch] = useReducer((state: IAdvisory, action: IReducerAction<IAction>) => {
        if (action.type === 'reset') return initialState
        if (action.type === 'update') {
            if (typeof action.data !== 'string') 
            return { ...state, ...action.data }
        }
        return { ...state, [action.type]: action.payload }
    }, initialState)
    const { url, setUrl, uploadImage, error: errorImage, progress, setError, loading: uploadingImage } = useImage()

    const router = useRouter()    
    const { id } = router.query

    const editorRef = useRef<TinyMCEEditor | null>(null);

    // console.log({advisory, url})


    const { loading: posting, error, data, post } = usePost({ 
        api: `/advisory/${id}`,
        method: 'PATCH',
        onSuccess: () => {
            toast('Advisory Board Member Added')
            dispatch({ type: 'reset'})
            editorRef.current?.setContent('')
            setUrl('')
            router.push('/admin/advisory')
        } 
    })

    const addMember = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        // dispatch({ type: 'description', payload: editorRef.current?.getContent() })
        post({...advisory, description: editorRef.current?.getContent()})
    }


    useEffect(() => {
        if (url) {
            dispatch({ type: 'image', payload: url })
        }
    }, [url])

    const fetchAdvisory = useCallback(
        async () => {
            try {
              setLoading(true)
              const res = await fetch(`/api/advisory/${id}`)
              const data = await res.json()
              
              if (!res.ok) throw new Error(data.message)
      
              // console.log({data})
              dispatch({ type: 'update', data: data })
            //   dispatch({ type: 'description', payload: editorRef.current?.getContent() })
              editorRef.current?.setContent(data.description)

            } catch (error) {
              console.log({error})
            }
            setLoading(false)
          },
      [id],
    )
     
    useEffect(() => {
        fetchAdvisory()
      }, [id, fetchAdvisory])

    return (
        <AdminLayout>
        <Head>
            <title>Brilliant Brains</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/faviconimg.png" />
        </Head>
        {(posting || loading || uploadingImage) && <Loader modalOpen={true} />}
        <div className='p-4 py-12 sm:px-12 h-full overflow-y-auto'>
            <div className="flex items-center gap-4 justify-between mb-16">
                <h1 className='text-3xl text-black/70 font-argentinum'>Edit Board Member</h1>
                <Button onClick={() => router.push("/admin/advisory")} className="text-white px-4 sm:px-6 py-2 rounded-xl text-sm">View Advisory</Button>
            </div>
            <form className="flex flex-col gap-4" onSubmit={addMember}>
                <div className="flex flex-col gap-1">
                    <label htmlFor="name" className="text-black/70">Name</label>
                    <input required onChange={(e) => dispatch({ type: 'name', payload: e.target.value })} value={advisory?.name} type="text" name="name" id="name" className="border border-black/20 rounded-md p-2" />
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor="email" className="text-black/70">Email</label>
                    <input required onChange={(e) => dispatch({ type: 'email', payload: e.target.value })} value={advisory?.email} type="email" name="email" id="email" className="border border-black/20 rounded-md p-2" />
                </div>
               
                {/* <div className="flex flex-col gap-1">
                    <span className="text-black/70">Upload Image</span>
                    <label className="border border-black/20 rounded-md p-2 min-h-[42px] max-h-12 whitespace-nowrap overflow-hidden bg-white" htmlFor="image">
                        {advisory?.image ? advisory?.image : ''}
                    </label>
                    <input type='file' required name='image' id='image' className='w-0 h-0 invisible' onChange={(e) => uploadImage(e.target.files![0])} />
                </div> */}
                <div className="flex flex-col gap-1">
                    <label htmlFor="number" className="text-black/70">Phone</label>
                    <input required onChange={(e) => dispatch({ type: 'number', payload: e.target.value })} value={advisory?.number} type="tel" name="number" id="number" className="border border-black/20 rounded-md p-2" />
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor="title" className="text-black/70">Title</label>
                    <input required onChange={(e) => dispatch({ type: 'title', payload: e.target.value })} value={advisory?.title} type="text" name="title" id="title" className="border border-black/20 rounded-md p-2" />
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor="description" className="text-black/70">Description</label>
                    {/* <textarea rows={5} required onChange={(e) => dispatch({ type: 'description', payload: e.target.value })} value={advisory?.description} name="description" id="description" className="border border-black/20 rounded-md p-2" /> */}
                    <TinyEditor editorRef={editorRef} />
                </div>
                <div className="flex flex-col gap-1">
                        <span className="text-black/70">Upload Image</span>
                         {advisory?.image &&
                            <Image width={100} height={100} src={advisory?.image} alt="" className="h-24 w-24 bg-gray-100 object-cover z-10 relative" />
                         }
                        <input type='file' name='image' id='image' className='' onChange={(e) => uploadImage(e.target.files![0])} />
                        {/* {uploadingImage && <p>Uploading Image {progress}%</p>} */}
                </div>
                <div className="flex items-center gap-4 mt-8">
                    <Button type='submit' className="text-white px-4 sm:px-6 py-2 rounded-xl text-sm">Update advisory</Button>
                    {/* <button onClick={() => dispatch({ type: 'reset' })} className="text-black/60 px-4 sm:px-6 py-2 rounded-md text-sm">Clear</button> */}
                </div>
            </form>
        </div>
        </AdminLayout>
    );
}


export default AuthHOC(EditBoardMember)
