import Head from "next/head";
import Script from "next/script";
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Link from "next/link";
import Image from 'next/image'
import Logo from "@/assets/logo.jpg"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Header />
        <section className="section min-h-screen pt-32">
          <div className="flex flex-col md:flex-row gap-4 md:gap-12">
            <div className="flex-1 flex flex-col gap-4">
              <p className="text-primary font-bold text-lg mb-3">STUDY WITH US</p>
              <h1 className="text-4xl md:text-6xl font-bold capitalize mb-3">Free Scholarship For Every Bright Student</h1>
              <p className="md:text-lg">The Brilliant Brain Scholarship Scheme is a scholarship management platform with a vision to ensuring that no person of school age is denied access to education because of his or her financial status, since it is the fundamental right of every child to receive  qualitative and functional education</p>
              <div className="flex justify-between bg-gray-100 rounded-lg max-w-md">
                <p className="my-4 ml-4">Lets get started</p>
                <button className="bg-primary text-white px-6 py-4 rounded-lg">Connect with us</button>
              </div>
            </div>
            <div className="flex-1 bg-gray-200 w-full min-h-96">
            </div>
          </div>
          <div className="flex justify-center py-12">
            <span>.</span>
            <span>.</span>
            <span>.</span>
          </div>
        </section>
        <section className="section mb-32">
          <div className="flex flex-col md:flex-row gap-4 md:gap-12">
            <div className="flex-1 flex flex-col gap-4">
              <p className="text-primary font-bold text-xl mb-3">About Us</p>
              <h2 className="text-4xl md:text-6xl font-bold capitalize mb-3">Qualified and Highly Equipped Learning</h2>
              <p className="md:text-lg mb-4">The Brilliant Brain Scholarship Scheme is a scholarship management platform with a vision to ensuring that no person of school age is denied access to education because of his or her financial status, since it is the fundamental right of every child to receive  qualitative and functional education</p>
              <button className="bg-primary text-white text-lg px-6 py-3 rounded-lg w-fit">Read More</button>
            </div>
            <div className="flex-1 bg-gray-200 w-full h-96 md:h-[500px]"></div>
          </div>
        </section>
        <section className="section mb-32 text-center">
          <div className="flex flex-col items-center gap-4 max-w-2xl mx-auto mb-12">
            <h2 className="text-primary font-bold text-2xl">Our Programmes</h2>
            <h3 className="text-4xl md:text-6xl font-bold capitalize mb-3">
              Pick Your Educational Level
            </h3>
          </div>
          <div className="grid md:grid-cols-4 gap-8">
            <div className="bg-gray-200 w-full rounded-2xl p-8 py-12 flex flex-col items-center gap-3">
              <div className="w-12 h-12 bg-gray-300"></div>
              <h5 className="text-2xl font-bold capitalize mb-3">Primary Education</h5>
              <p className="text-left">Are you a student that needs a scholarship? or a teacher who wish to</p>
            </div>
            <div className="bg-gray-200 w-full rounded-2xl p-8 py-12 flex flex-col items-center gap-3">
              <div className="w-12 h-12 bg-gray-300"></div>
              <h5 className="text-2xl font-bold capitalize mb-3">Primary Education</h5>
              <p className="text-left">Are you a student that needs a scholarship? or a teacher who wish to</p>
            </div>
            <div className="bg-gray-200 w-full rounded-2xl p-8 py-12 flex flex-col items-center gap-3">
              <div className="w-12 h-12 bg-gray-300"></div>
              <h5 className="text-2xl font-bold capitalize mb-3">Primary Education</h5>
              <p className="text-left">Are you a student that needs a scholarship? or a teacher who wish to</p>
            </div>
            <div className="bg-gray-200 w-full rounded-2xl p-8 py-12 flex flex-col items-center gap-3">
              <div className="w-12 h-12 bg-gray-300"></div>
              <h5 className="text-2xl font-bold capitalize mb-3">Primary Education</h5>
              <p className="text-left">Are you a student that needs a scholarship? or a teacher who wish to</p>
            </div>
          </div>
        </section>
        <section className="section mb-32">
          <div className="flex flex-col items-center gap-4 max-w-xl mx-auto mb-12 text-center">
            <h3 className="text-4xl md:text-6xl font-bold capitalize mb-3">Which One is Suitable For You</h3>
            <p>Are you a student that needs a scholarship? or a teacher who wish to Upgrade his/her Knowledge </p>
          </div>
          <div className="flex flex-col md:flex-row md:justify-center gap-8">
            <div className="max-w-md p-4 md:p-20 shadow-xl flex flex-col justify-center rounded-xl">
              <div className="max-w-sm flex flex-col gap-4 justify-center text-center mb-8">
                <div className="bg-gray-200 h-44 w-44 rounded-full mx-auto"></div>
                <h4 className="text-2xl font-bold">Student</h4>
              </div>
              <div className="flex flex-col gap-3 font-bold mb-12">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-red-100"></div>
                  <p>Lorem lorem lorem lorem</p>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-red-100"></div>
                  <p>Lorem lorem lorem lorem</p>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-red-100"></div>
                  <p>Lorem lorem lorem lorem</p>
                </div>
              </div>
              <button className="md:text-lg bg-primary text-white py-3.5 px-8 w-fit rounded-3xl mx-auto">View Details</button>
            </div>
            <div className="max-w-md p-4 md:p-20 shadow-xl flex flex-col justify-center rounded-xl bg-primary text-white">
              <div className="max-w-sm flex flex-col gap-4 justify-center text-center mb-8">
                <div className="bg-gray-200 h-44 w-44 rounded-full mx-auto"></div>
                <h4 className="text-2xl font-bold">Teacher</h4>
              </div>
              <div className="flex flex-col gap-3 font-bold mb-12">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-red-100"></div>
                  <p>Lorem lorem lorem lorem</p>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-red-100"></div>
                  <p>Lorem lorem lorem lorem</p>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-red-100"></div>
                  <p>Lorem lorem lorem lorem</p>
                </div>
              </div>
              <button className="md:text-lg bg-red-600 text-white py-3.5 px-8 w-fit rounded-3xl mx-auto">View Details</button>
            </div>
          </div>
        </section>
        <section className="section mb-32 text-center">
         <div className="flex flex-col items-center gap-4 max-w-3xl mx-auto mb-12 text-center">
            <h3 className="text-4xl md:text-6xl font-bold capitalize mb-3">Our <br /> Ambassadors</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, explicabo recusandae necessitatibus voluptas nobis voluptatum nesciunt incidunt facilis, a provident dicta repudiandae ratione mollitia fuga deleniti! Alias explicabo aliquid repellat! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad repellendus adipisci qui ratione excepturi unde inventore aspernatur. Accusamus numquam, officia laboriosam similique nemo repellat libero consequatur eum minima quas doloremque. </p>
          </div>
          <div className="flex flex-col md:flex-row md:justify-center items-center gap-8">
            <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
            <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
            <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
          </div>
        </section>
        <section className="section mb-32 py-20 px-4 flex flex-col items-center gap-4 bg-red-400 text-white">
          <div className="flex flex-col items-center gap-4 max-w-3xl text-center">
            <h3 className="text-4xl md:text-6xl font-bold capitalize mb-2">Looking for a bright new future. It starts here</h3>
            <p className="mb-4">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem illo nostrum aperiam voluptatibus vitae? Quisquam laboriosam enim ipsum modi! Molestiae eveniet fugit perferendis quaerat ex et porro beatae enim quas!</p>
            <button className="p-5 px-12 text-lg rounded-full font-bold bg-white text-black">Get in Touch</button>
          </div>
        </section>
        <section className="section mb-32 text-center">
          <div className="flex flex-col items-center gap-4">
            <h3 className="text-4xl md:text-6xl font-bold capitalize mb-10">Scholarship <br /> Winners</h3>
          </div>
          <div className="flex flex-col md:flex-row md:justify-center gap-8 mb-8">
             <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
             <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
             <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
          </div>
          <div className="flex flex-col md:flex-row md:justify-center gap-8">
             <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
             <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
             <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
          </div>
        </section>
        <section className="section mb-32 ">
          <div className="flex flex-col md:flex-row gap-4 md:gap-12 bg-primary text-white p-4 md:p-16">
            <div className="flex-1 flex flex-col gap-4">
              <h2 className="text-4xl md:text-6xl font-bold capitalize mb-3">Become Part of Us on Our Platform</h2>
              <p className="md:text-lg mb-4">The Brilliant Brain Scholarship Scheme is a scholarship management platform with a vision to ensuring that no person of school age is denied access to education because of his or her financial status, since it is the fundamental right of every child to receive  qualitative and functional education</p>
              <div className="grid grid-cols-2 gap-5 mb-4 max-w-fit">
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-full bg-red-100"></div>
                    <p>Primary Education</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-full bg-red-100"></div>
                    <p>Primary Education</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-full bg-red-100"></div>
                    <p>Primary Education</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-full bg-red-100"></div>
                    <p>Primary Education</p>
                  </div>
              </div>
              <button className="bg-yellow-400 text-white text-lg px-6 py-3 rounded-lg w-fit">Apply Now</button>
            </div>
            <div className="flex-1 bg-gray-200 w-full h-96 md:h-[500px]"></div>
          </div>
        </section>
        <section className="section mb-32 text-center">
          <h2 className="text-4xl md:text-6xl font-bold capitalize mb-12">News & <br />Updates</h2>
          <div className="grid md:grid-cols-3 md:h-[500px] gap-8">
            <div className="bg-gray-200 w-full h-96"></div>
            <div className="bg-gray-200 w-full h-96 place-self-center"></div>
            <div className="bg-gray-200 w-full h-96 place-self-end"></div>
          </div>
        </section>
        <section className="section mb-32 ">
          <div className="flex flex-col md:flex-row gap-4 md:gap-12 bg-primary text-white p-4 md:p-16">
            <div className="flex-1 flex flex-col gap-4">
              <h3 className="text-4xl md:text-6xl font-bold capitalize mb-3">Sign up for Our Scholarship Program Now</h3>
              <p className="md:text-lg mb-4">The Brilliant Brain Scholarship Scheme is a scholarship management platform with a vision to ensuring that no person of school age is denied access to education because of his or her financial</p>
            </div>
            <form className="flex-1 flex flex-col gap-4 w-full">
              <input className="p-5 px-8 rounded-full" type="text" name="username" id="username" placeholder="username" />
              <input className="p-5 px-8 rounded-full" type="email" name="email" id="email" placeholder="Enter your email address" />
              <select className="p-5 px-8 rounded-full" name="ty[e" id="type">
                <option value="student">Student</option>
              </select>
              <button className="bg-black text-white font-medium text-lg px-14 py-4 rounded-full w-fit">Send Request</button>
            </form>
          </div>
        </section>
        <section className="section mb-32 text-center">
          <div className="flex flex-col items-center gap-4">
          <h3 className="text-4xl md:text-6xl font-bold capitalize mb-10">Advisory Board <br /> Members</h3>
          </div>
          <div className="flex flex-col md:flex-row md:justify-center gap-8">
            <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
            <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
            <div className="max-w-sm flex flex-col gap-4 justify-center">
              <div className="bg-gray-200 h-72 w-72 rounded-full"></div>
              <div>
                <h4 className="text-3xl font-bold">John Doe</h4>
                <span className="text-primary font-bold text-xl">Lorem Ileum</span>
              </div>
            </div>
          </div>
        </section>
        <Footer />
        <section className="section py-6">
          <div className="flex items-center gap-7">
            <Link href={"/"}>
              <Image src={Logo} className='w-20 h-16' alt=''></Image>
            </Link>
            <p className="font-bold text-xl">
              BRILLIANT BRAIN SCHOLARSHIP 2023
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
